name: project_4
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dot_navigation_bar: ^1.0.2
  syncfusion_flutter_core: ^23.1.43
  syncfusion_flutter_sliders: ^23.1.43
  shimmer: ^3.0.0
  flutter_advanced_drawer: ^1.3.5
  glassmorphism_ui: ^0.3.0
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
    - family: DMSerifText
      fonts:
        - asset: assets/fonts/SerifText-Regular.ttf
  assets:
    - assets/images/